name:                Studienarbeit
version:             0.1.0.0
github:              "https://github.com/ob-fun-ws18/studienarbeit-roteroktober"
license:             BSD3
author:              "Fabian Sinning, Dominik Schmidt"
maintainer:          "schmid82@hm.edu"
copyright:           "2019 Fabian Sinning, Dominik Schmidt"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Studienarbeit#readme>

dependencies:
- base 
- network
- bytestring ==0.10.*
- threepenny-gui == 0.8.3.0
- mtl
- random >=1.0
- array
- atomic-primops
- exceptions
- monad-control
- stm
- transformers
- containers
- syb
- ghc-prim
- regex-base >=0.93
- semigroups
- regex-posix >=0.95.1
- parsec
- regex-compat

library:
  source-dirs: src

executables:
  Studienarbeit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Studienarbeit

tests:
  Studienarbeit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Studienarbeit
